baseURL = 'https://www.sandeepmore.com/'
languageCode = "en-us"
title = "Sandeep R. Moré"
theme = "cactus"
copyright = "srmore.io" # cactus will use title if copyright is not set
disqusShortname = "sandeep" # Used when comments is enabled. Cactus will use site title if not set
googleAnalytics = "UA-3820432-5"
# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4


#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  #description = "An engineer by trade, tinkering and working on security around big data. I am also an  [Apache](https://www.apache.org/) Committer and a PMC member for Apache Knox project. When not working on real world problems you may find me working on home automation projects or playing boardgames. I sometimes blog, topics are mostly technical but not always. I am also a firm believer in [opensource](https://en.wikipedia.org/wiki/Open-source_software) software and its values."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/moresandeep" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # only disqus, utterances, and cactus_comments is supported
    
  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/moresandeep"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/moresandeep/"
  [[params.social]]
    name = "email"
    link = "hello@srmore.io"  # no need for "mailto:" in the head
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/moresandeep"

